remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
title: [Podcast | Kris Kras - Door het Lichaam]
description: [Kris en Annemiek maken een luchtige educatieve podcast, speciaal voor kinderen, over het menselijk lichaam en medische onderwerpen.]
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
